# general
gpu_id: 2
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
dataset_save_path: ~
save_dataloaders: False
dataloaders_save_path: ~
log_wandb: False
wandb_project: 'recbole'

# training settings
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
#threshold:
#    rating: 1
neg_sampling:
eval_step: 1
stopping_step: 20
#clip_grad_norm: ~
clip_grad_norm:  {'max_norm': 5, 'norm_type': 2}
weight_decay: 0.0
loss_decimal_place: 4
require_pow: False

# evaluation settings
eval_args: 
  split: {'LS':'valid_and_test'}
  group_by: None
  order: TO
  mode: full
repeatable: False
metrics: ["Recall","NDCG","MRR","Hit","Precision"]
topk: [5, 10, 20, 50]
valid_metric: Recall@20
valid_metric_bigger: True
eval_batch_size: 4096
metric_decimal_place: 4